export type ConfigureArgs = {
    /**
     * The client key. Obtainable through WorldPay's API access key
     */
	clientKey: string;
}

declare function configure(options: ConfigureArgs): void;

export type CardArgs = {
    /**
     * The card holder's name
     */
    name: string;

    /**
     * The card number
     */
    number: string;

    /**
     * The card's expiry month
     */
    expiryMonth: string;

    /**
     * The card's expiry year
     */
    expiryYear: string;

    /**
     * The card's security number
     */
    cvc: string;
}

interface CreateTokenResult {
    /**
     * The response code from WorldPay
     */
    code: number;
    /**
     * The response content from WorldPay
     */
    response: CreateTokenResponse;
}

interface CreateTokenResponse {
    /**
     * The token generated (if successful)
     */
    token?: string;
    /**
     * The payment method returned back (if successful)
     */
    paymentMethod?: {
        maskedCardNumber: string;
        expiryYear: string;
        expiryMonth: string;
        cardType: string;
        name: string;
    }
}

/**
 * Returns a token generated by WorldPay, given card credentials
 */
declare function createToken(card: CardArgs): Promise<CreateTokenResult>;

interface CardValidationResult {
    /**
     * The card's expiry date
     */
    expiry: boolean;
    /**
     * The card's security number
     */
    cvc: boolean;
    /**
     * The card name
     */
    name: boolean;
    /**
     * The card number
     */
    number: boolean;
}

/**
 * Validates the user's card details
 */
declare function validateCardDetails(card: CardArgs): Promise<CardValidationResult>;
